import stylisticJs from '@stylistic/eslint-plugin-js'

export default {
  name: 'frontera:rules:stylistic',
  plugins: {
    '@stylistic/js': stylisticJs
  },
  rules: {
    '@stylistic/js/array-bracket-spacing': ['error', 'always'],
    '@stylistic/js/arrow-parens': ['warn', 'always'],
    '@stylistic/js/arrow-spacing': ['error', { after: true, before: true }],
    '@stylistic/js/block-spacing': ['error', 'always'],
    '@stylistic/js/brace-style': ['error', '1tbs', { allowSingleLine: false }],
    '@stylistic/js/comma-dangle': ['warn', 'always-multiline'],
    '@stylistic/js/comma-spacing': ['error', { after: true, before: false }],
    '@stylistic/js/comma-style': ['error', 'last'],
    '@stylistic/js/computed-property-spacing': ['error', 'never'],
    '@stylistic/js/dot-location': ['error', 'property'],
    '@stylistic/js/eol-last': 'error',
    '@stylistic/js/func-call-spacing': 'error',
    '@stylistic/js/generator-star-spacing': ['error', 'before'],
    '@stylistic/js/indent': ['error', 4, { SwitchCase: 1 }],
    '@stylistic/js/jsx-quotes': ['warn', 'prefer-double'],
    '@stylistic/js/keyword-spacing': ['error'],
    '@stylistic/js/linebreak-style': ['off', 'unix'],
    '@stylistic/js/lines-around-comment': ['error', { beforeBlockComment: true }],
    '@stylistic/js/max-len': ['error', 132],
    '@stylistic/js/new-parens': 'error',
    '@stylistic/js/no-confusing-arrow': 'error',
    // to check
    '@stylistic/js/no-extra-parens': 'off',
    '@stylistic/js/no-floating-decimal': 'error',
    '@stylistic/js/no-mixed-spaces-and-tabs': 'error',
    '@stylistic/js/no-multi-spaces': 'error',
    '@stylistic/js/no-multiple-empty-lines': 'error',
    '@stylistic/js/no-trailing-spaces': ['error', { ignoreComments: true }],
    '@stylistic/js/object-curly-spacing': ['warn', 'always'],
    '@stylistic/js/operator-linebreak': ['error', 'after', { overrides: { ':': 'ignore', '?': 'ignore' } }],
    '@stylistic/js/padded-blocks': ['error', 'never'],
    '@stylistic/js/quote-props': ['warn', 'consistent-as-needed'],
    '@stylistic/js/quotes': ['warn', 'double'],
    '@stylistic/js/semi': ['error', 'always'],
    '@stylistic/js/semi-spacing': ['error', { after: true, before: false }],
    '@stylistic/js/space-before-blocks': ['error', 'always'],
    '@stylistic/js/space-in-parens': ['error', 'never'],
    '@stylistic/js/space-infix-ops': ['error', { int32Hint: true }],
    '@stylistic/js/space-unary-ops': 'error',
    '@stylistic/js/spaced-comment': ['error', 'always'],
    '@stylistic/js/wrap-iife': ['error', 'outside'],
    '@stylistic/js/wrap-regex': 'error',
    'consistent-this': ['warn', 'self'],
    'func-names': 'off',
    'func-style': ['off', 'declaration'],
    'id-length': ['error', { exceptions: ['i', '_'], max: 32, min: 2 }],
    'max-depth': ['error', 8],
    'max-nested-callbacks': ['error', 8],
    'max-params': ['error', 8],
    'new-cap': ['error', { capIsNewExceptionPattern: '^Selector' }],
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'off',
    'no-bitwise': 'off',
    'no-continue': 'off',
    'no-inline-comments': 'off',
    'no-lonely-if': 'error',
    'no-negated-condition': 'off',
    'no-nested-ternary': 'error',
    'no-object-constructor': 'error',
    'no-plusplus': 'off',
    // to check
    'no-prototype-builtins': 'off',
    'no-ternary': 'off',
    'no-underscore-dangle': 'off',
    'no-unneeded-ternary': 'error',
    // to check
    'no-useless-escape': 'off',
    'one-var': 'off',
    'operator-assignment': ['warn', 'never'],
    'sort-vars': 'off',
  }
}
