export default {
  rules: {
    'array-bracket-spacing': ['error', 'always'],
    'block-spacing': ['error', 'always'],
    'brace-style': ['error', '1tbs', { allowSingleLine: false }],
    'comma-dangle': ['warn', 'always-multiline'],
    'comma-spacing': ['error', { after: true, before: false }],
    'comma-style': ['error', 'last'],
    'computed-property-spacing': ['error', 'never'],
    'consistent-this': ['warn', 'self'],
    'eol-last': 'error',
    'func-names': 'off',
    'func-style': ['off', 'declaration'],
    'id-length': ['error', { exceptions: ['i', '_'], max: 32, min: 2 }],
    indent: ['error', 4, { SwitchCase: 1 }],
    'jsx-quotes': ['warn', 'prefer-double'],
    'keyword-spacing': ['error'],
    'linebreak-style': ['off', 'unix'],
    'lines-around-comment': ['error', { beforeBlockComment: true }],
    'max-depth': ['error', 8],
    'max-len': ['error', 132],
    'max-nested-callbacks': ['error', 8],
    'max-params': ['error', 8],
    'new-cap': ['error', { capIsNewExceptionPattern: '^Selector' }],
    'new-parens': 'error',
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'off',
    'no-bitwise': 'off',
    'no-continue': 'off',
    'no-inline-comments': 'off',
    'no-lonely-if': 'error',
    'no-mixed-spaces-and-tabs': 'error',
    'no-multiple-empty-lines': 'error',
    'no-negated-condition': 'off',
    'no-nested-ternary': 'error',
    'no-new-object': 'error',
    'no-plusplus': 'off',
    'no-prototype-builtins': 'off',
    'no-spaced-func': 'error',
    'no-ternary': 'off',
    'no-trailing-spaces': ['error', { ignoreComments: true }],
    'no-underscore-dangle': 'off',
    'no-unneeded-ternary': 'error',
    'no-useless-escape': 'off',
    'object-curly-spacing': ['warn', 'always'],
    'one-var': 'off',
    'operator-assignment': ['warn', 'never'],
    'operator-linebreak': ['error', 'after', { overrides: { ':': 'ignore', '?': 'ignore' } }],
    'padded-blocks': ['error', 'never'],
    'quote-props': ['warn', 'consistent-as-needed'],
    quotes: ['warn', 'double'],
    'require-jsdoc': [
      'off',
      {
        require: {
          ClassDeclaration: false,
          FunctionDeclaration: true,
          MethodDefinition: true,
        },
      },
    ],
    semi: ['error', 'always'],
    'semi-spacing': ['error', { after: true, before: false }],
    'sort-vars': 'off',
    'space-before-blocks': ['error', 'always'],
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': ['error', { int32Hint: true }],
    'space-unary-ops': 'error',
    'spaced-comment': ['error', 'always'],
    'wrap-regex': 'error',
  }
}
